server:
  port: ${PORT:8080}
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${JDBC_DATABASE_PASSWORD:}
    url: ${JDBC_DATABASE_URL:}
    username: ${JDBC_DATABASE_USERNAME:}
    hikari:
      connection-timeout: 80000
      maximum-pool-size: 10
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 5MB
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    database-platform: ${SPRING_JPA_DATABASE-PLATFORM:}
    hibernate:
     ddl-auto: update
    open-in-view: false
    properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
carousel:
  images: Aerosmith.jpg,madonna.jpg,metallica.jpg,queen.jpg,rolling stones.jpg,iron
    maiden.jpg
  refresh-cron: 0 */9 * * * *
            #------------------------------------------------------------------------



# password: ${JDBC_DATABASE_PASSWORD:}
# url: ${JDBC_DATABASE_URL:}
# username: ${JDBC_DATABASE_USERNAME:}

#                properties:
#                  hibernate:
#                    dialect: org.hibernate.dialect.PostgreSQLDialect
#                    format_sql: true

